apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brandex-client-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: brandex-client
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    web-client: brandex-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: brandex-client
spec:
  selector:
    matchLabels:
      web-client: brandex-client
  template:
    metadata:
      labels:
        web-client: brandex-client
        system: client
    spec:
      containers:
      - name: brandex-client
        image: petarhrusanov/brandexautomationtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ApplicationSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        volumeMounts:
        - name: brandex-client-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: brandex-client-data
        persistentVolumeClaim:
          claimName: brandex-client-data