apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brandex-client-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: brandex-client
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 80
  selector:
    web-client: brandex-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: brandex-client
spec:
  selector:
    matchLabels:
      web-client: brandex-client
  template:
    metadata:
      labels:
        web-client: brandex-client
        system: client
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-client: brandex-client
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: brandex-client
        image: petarhrusanov/brandexautomationtest:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ApplicationSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: ApplicationSettings__SeedInitialData
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: seed-initial-data
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: brandex-service-connection-string
        - name: ConnectionStrings__CronJobsConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: brandex-service-cron-jobs-connection-string
        volumeMounts:
        - name: brandex-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: brandex-service-data
        persistentVolumeClaim:
          claimName: brandex-service-data